# spring boot 的全部配置属性
# http://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/htmlsingle/#common-application-properties

# 我的机器上的8080端口我分配给了zookeeper
server:
  port: 8180
# redis的配置文件
spring:
  redis:
    host: localhost
    port: 6378
    database: 0
    password: null
    timeout: 1000
    #Sentinel配置
    #spring.redis.sentinel.master=127.0.0.1:6378
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26380
    pool:
      #当连接池消耗完毕时阻塞直到超时
      blockWhenExhausted: true
      #最大空闲连接数
      maxIdle: 10
      #最大连接数
      maxTotal: 10
      #最长空闲时间,一分钟
      minEvictableIdleTimeMillis: 60000
  #配置springmvc静态文件
  mvc:
    static-path-pattern: /*.html
